version: 2.1

orbs:
  ruby: circleci/ruby@2.1.3
  qlty: qltysh/qlty-orb@0.0.11

executors:
  default:
    parameters:
      ruby-version:
        description: "ruby version tag"
        default: "3.4.4"
        type: string
    docker:
      - image: cimg/ruby:<<parameters.ruby-version>>

jobs:
  doc:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec yard doc
      - store_artifacts:
          path: doc
          destination: doc

  rspec:
    parameters:
      ruby-version:
        description: "ruby version tag"
        type: string
    executor:
      name: default
      ruby-version: <<parameters.ruby-version>>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - qlty/coverage_publish:
          files: ./coverage/.resultset.json

  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  version: 2.1
  build:
    jobs:
      - doc
      - rspec:
          matrix:
            parameters:
              ruby-version:
                - "3.4.4"
                - "3.3.7"
                - "3.2.6"
      - rubocop
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
